inherit_from: ../../.hound.yml

AllCops:
  Exclude:
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'config/initializers/devise.rb'
    - 'db/migrate/*_devise_*.rb'
    - 'db/schema.rb'
    - 'vendor/**/*'
