inherit_from: ../../.hound.yml

AllCops:
  Exclude:
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'config/initializers/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'features/support/env.rb'
    - 'lib/tasks/cucumber.rake'
    - 'script/*'
    - 'vendor/**/*'

Metrics/LineLength:
  Exclude:
    - 'features/step_definitions/*_steps.rb'
