source 'https://rubygems.org'

gem 'rails', '4.2.0.beta1'
gem 'pg'
gem 'sass-rails', '~> 5.0.0.beta1'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'bootstrap-sass', '~> 3.2.0'
gem 'autoprefixer-rails'
gem 'select2-rails', '~> 3.5.9.1'
gem 'jquery-rails', '~> 4.0.0.beta2'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'psych', '~> 2.0', platforms: :rbx
gem 'haml-rails'
gem 'devise'
gem 'cancan'
gem 'kaminari'
gem 'requirejs-rails'
gem 'eve_central', require: false, path: '../eve_central/'

group :development, :test do
  gem 'web-console', '~> 2.0.0.beta4'
  gem 'rspec-rails', '~> 3.0.0'
  gem 'cucumber-rails', require: false
  gem 'database_cleaner', require: false
  gem "factory_girl_rails", "~> 4.0", require: false
  gem 'rake-progressbar', require: false
  gem "rubysl-irb", require: false
  gem "pry"
  gem "vcr", require: false
  gem "webmock", require: false
end
