source "https://rubygems.org"


gem "rails", "4.2.0"
gem "pg"
gem "coffee-rails", "~> 4.1.0"
gem "therubyracer", platforms: :ruby

gem "jquery-rails"
gem "jbuilder", "~> 2.0"
gem "sdoc", "~> 0.4.0", group: :doc
gem "delivery", github: "djkotowski/delivery"
gem "omniauth-delivery-food"
gem "haml-rails"
gem "devise"
gem "bootstrap-sass", "~> 3.3.5"
gem "bootstrap_form"
gem "devise-bootstrap-views"

group :development, :test do
  gem "byebug"
  gem "cucumber-rails", "~> 1.4.2", require: false
  gem "database_cleaner", "~> 1.5"
  gem "rspec-rails", "~> 3.2.3", require: false
  gem "web-console", "~> 2.0"
end

