# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68f04cdcdb3be8f004cae0b345d7f41eb20bb5d173b7b1d57c033fe647c8e56654d726a22469cad3dcaa430a55799bc68535ce8ec6a1abbb303a299e7678380b

test:
  secret_key_base: 143e1a42cb7d3cef4a11ac0b23957e9821f9555daa7331f8b3fe21743dd65f139bd56578bff3f7a432389ba7c3cc80fe5f8969e1a3e5914ec9acdc519f9a0f99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
