source "https://rubygems.org"

gem "rails", "4.2.0"
gem "pg"
gem "coffee-rails", "~> 4.1.0"
gem "therubyracer", platforms: :ruby
gem "jquery-rails"
gem "sass-rails"
gem "sprockets-rails"
gem "jbuilder", "~> 2.0"
gem "sdoc", "~> 0.4.0", group: :doc
gem "haml-rails"
gem "bootstrap-sass", "~> 3.3.5"
gem "bootstrap_form"
gem "devise"
gem "devise-bootstrap-views"
gem "figgy"
gem "httplog"
gem "interactor"

group :development, :test do
  gem "byebug"
  gem "pry"
  gem "cucumber-rails", "~> 1.4.2", require: false
  gem "factory_girl_rails"
  gem "faker"
  gem "database_cleaner", "~> 1.5"
  gem "interactor-rails", require: false
  gem "rspec-rails", "~> 3.2.3", require: false
  gem "simplecov", require: false
  gem "web-console", "~> 2.0"
  gem "webmock"
  gem "vcr"
end
