# Generated by cucumber-sinatra. (2015-02-04 11:18:53 -0600)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'overlord.rb')

require 'capybara'
require 'capybara/cucumber'
require 'capybara/session'
require 'capybara/poltergeist'
require 'rspec'

Capybara.app = Overlord
Capybara.javascript_driver = :poltergeist

class OverlordWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  OverlordWorld.new
end
