# Generated by cucumber-sinatra. (2015-02-04 11:18:53 -0600)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'overlord.rb')

require 'capybara'
require 'capybara/cucumber'
require 'capybara/session'
require 'capybara-screenshot/cucumber'
require 'capybara/poltergeist'
require 'rspec'
require 'pry'
require 'simplecov'
SimpleCov.start

Capybara.app = Overlord::App
Capybara.javascript_driver = :poltergeist
Capybara.save_and_open_page_path = 'tmp/capybara'

class OverlordWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  OverlordWorld.new
end
