AllCops:
  Exclude:
    - triangle_facts/*.rb
    - supportive/supportive.rb
    - local_events_feed/Rakefile
    - local_events_feed/config/*.rb
    - local_events_feed/db/schema.rb
    - local_events_feed/bin/*
    - local_events_feed/lib/tasks/cucumber.rake
    - local_events_feed/features/support/env.rb
    - local_events_feed/Gemfile*

# C: Missing top-level module documentation comment.
Style/Documentation:
  Enabled: false

# C: Prefer reduce over inject.
Style/CollectionMethods:
  PreferredMethods:
    reduce: 'inject'

# C: Use each_with_object instead of inject.
Style/EachWithObject:
  Enabled: false

# C: Removing the preference for string single quotes
Style/StringLiterals:
  Enabled: false

#C: Prefer fail over raise
Style/SignalException:
  Enabled: false

Style/TrailingComma:
  EnforcedStyleForMultiline: comma

# This never works for validations
Style/AlignHash:
  EnforcedLastArgumentHashStyle: ignore_implicit

# align multi-line params with previous line
Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

# indent `when` clause one step from `case`
Style/CaseIndentation:
  IndentOneStep: true

# don't force crappy var names for reduce/inject loops...
Style/SingleLineBlockParams:
  Enabled: false

# stop nesting so hard.
Metrics/BlockNesting:
  Max: 2

# short methods, man...
Metrics/MethodLength:
  Max: 7

# fewer parameters
Metrics/ParameterLists:
  Max: 3

# skip for this exercise
Style/AsciiComments:
  Exclude:
    - scheduler/schedule.rb
