# Generated by cucumber-sinatra. (2014-10-02 15:29:41 -0500)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/overlord.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Overlord
# Capybara.default_driver = :selenium

class OverlordWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  OverlordWorld.new
end
