# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e815b1b69dbb45cb239c37339673c39919e623f83d45f770bafea23e40b516da3681581fa98649af0e9402c98af689c095f160e5c6af6594f94d287ce119a376

test:
  secret_key_base: a987ef34546a6112a3054c88793058a8aedc1020711f319435e71aee34bca7ac20a95debbaf2d28988c0ec311e7c6d2bbe3c2d04c8f72eadd6d58af4e0634c74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
