source 'https://rubygems.org'

gem 'rails', '4.2.0'
gem 'sqlite3'
gem 'bootstrap-sass'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'yahoo-finance'
gem 'haml'
gem 'devise'
gem 'chartkick'
gem "font-awesome-rails"

group :development, :test do
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'pry-rails', '0.3.3'
  gem 'pry-byebug', '~> 2.0.0'
  gem 'pry-rescue', '~> 1.4.1'
  gem 'pry-stack_explorer', '~> 0.4.9.1'
  gem 'rubocop'
  gem 'cucumber-rails', :require => false
  gem 'capybara'
  gem 'rspec-rails', '~> 3.0'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'selenium-webdriver'
end

