source 'https://rubygems.org'

gem 'rails', '~> 5.0'
gem 'pg'
gem 'sass-rails'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'icalendar'

group :development, :test do
  gem 'foreman'
  gem 'rspec-rails', '~> 3.0.0'
  gem 'factory_bot_rails'
  gem 'shoulda'
  gem 'faker'
  gem 'ruby-progressbar'
  gem 'pry'
  gem 'rspec-collection_matchers'
end

group :test do
  gem 'database_cleaner'
end
