source 'https://rubygems.org'

gem 'rails', '4.1.4'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'bootstrap-sass'
gem 'httparty'
gem 'figgy'

gem 'devise'
gem 'nokogiri'
gem 'chronic'

gem 'icalendar'
# gem "simple_calendar", "~> 1.1.0"

group :development do
  gem 'better_errors'
  gem 'binding_of_caller', :platforms=>[:mri_21]
  gem 'rails_layout'
end

group :development, :test do
  gem 'pry'
  gem 'pry-debugger'
  gem 'pry-rails'
  gem 'pry-rescue'
  gem 'rspec-rails', '~> 3.0.0'
  gem 'capybara'
end
