source 'https://rubygems.org'

gem 'rails', '4.1.4'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'pg'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'bootstrap-sass'
gem 'bootstrap_sortable_rails'
gem 'bootstrap-tooltip-rails'

# Because ERB blows big chunks!
gem 'haml'

# HTTP Client
gem 'httparty'

# Config file management
gem 'figgy'

# Rails caching for performance
gem 'lookup_by'

# DB tool to add foreign key constraints
gem 'foreigner'

# Industry standard for adding user functionality to apps
gem 'devise'

gem 'nokogiri'
gem 'chronic'

gem 'icalendar'
# gem "simple_calendar", "~> 1.1.0"

# Background async processing
gem 'resque'
gem 'resque-scheduler'
gem 'foreman'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller', :platforms=>[:mri_21]
  gem 'rails_layout'
end

group :development, :test do
  gem 'rubocop'
  gem 'factory_girl_rails'
  gem 'pry'
  gem 'pry-debugger'
  gem 'pry-rails'
  # gem 'capybara'
  gem 'pry-rescue'
  gem 'rspec-rails', '~> 3.0.0'
end
