source 'https://rubygems.org'
ruby '2.1.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.6'
# Use postgresql as the database for Active Record
gem 'pg', '0.17.1'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
gem 'autoprefixer-rails'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes

# Use jquery as the JavaScript library
gem 'jquery-rails', '3.1.2'
gem 'jquery-turbolinks'

gem 'turbolinks', '2.3.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Read more: https://github.com/rails/spring
gem 'spring', group: :development

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'
group :development do
  gem 'puma', '~> 2.9.1'
end
gem 'activeadmin', github: 'activeadmin'
gem 'devise', '~> 3.3.0'
gem 'activevalidators', '3.1.2'
gem 'twitter-bootstrap-rails'
gem 'therubyracer',  platforms: :ruby
gem 'less-rails'
gem 'nokogiri'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
gem 'fullcalendar-rails', :github => "enovajuan/fullcalendar-rails"
group :development, :test do
  gem 'ruby_debugger'
  gem 'factory_girl_rails', '~> 4.4.0'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'debase', '~> 0.0.9'
  gem 'database_cleaner', '~> 1.3.0'

  gem 'ruby-debug-ide', '~> 0.4.22'
  gem 'simplecov'
  gem 'simplecov-teamcity-summary'
end
