---
contacts:
  customer_service:
    telephone: "1-800-EAT-PORK"
    email: "n@body2.talk.to"
    mail:
      - "Nobody's Reading This"
      - 1001 Bit Bucket Blvd.
      - "Dev Null, Nowhere 0xFFFFFF"

