# Generated by cucumber-sinatra. (2015-08-07 09:41:45 -0500)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'shopping_cart.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = shopping_cart

class shopping_cartWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  shopping_cartWorld.new
end
