# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eff5b5769e909ffddc558fca45265f21257d0c1c31e13a7a4fadd92cfbb0e0e5d4b9dff85669df67e17465f519512edf670176973d2f63e5d932efaffbaefdf6

test:
  secret_key_base: 842a05eef3ddfd9fa5c48f8da37133c4ce175bdb7d989ec9ef1f93697aef7e94edbfdfb5049be399c9a2d1af93623841e7b204d66e5dfcde92a03155c693b431

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
