source 'http://rubygems.org'

gem 'activesupport', '~> 4.2.0'

group :test do
  gem 'rspec'
  gem 'pry', '0.10.1'
  gem 'pry-byebug', '~> 2.0.0'
  gem 'pry-rescue', '~> 1.4.1'
  gem 'pry-stack_explorer', '~> 0.4.9.1'
  gem 'simplecov', '~> 0.8.2', :require => false
  gem 'faker', '~> 1.4.3'
end
