source "https://rubygems.org"

gem "sinatra"

group :test do
  gem "rspec"
  gem "simplecov", require: false
  gem "cucumber"
  gem "cucumber-sinatra"
  gem "capybara"
  gem "capybara-webkit"
  gem "rack"
  gem "rack-test"
  gem "guard"
  gem "guard-cucumber"
  gem "guard-rspec"
  gem "foreman"
end
