# A sample Gemfile
source "https://rubygems.org"

ruby "2.0.0"

gem "sinatra"

gem "cucumber"
gem "cucumber-sinatra"
gem "coffee-script"

gem "capybara"

gem 'rspec-rails' # library of Rails assertions
gem "selenium-webdriver"
gem 'capybara-screenshot', :group => :test
