// Generated by CoffeeScript 1.8.0
(function() {
  var init_dropdown, init_message_list, init_search_box, init_sidebar, resize_main_pane;

  init_dropdown = function() {
    return $('.dropdown-toggle').click(function(e) {
      var button;
      button = $(e.currentTarget);
      button.toggleClass('active');
      return $(button.attr('data-target')).toggleClass('hidden');
    });
  };

  init_message_list = function() {
    return $('input[name="selected_message"]').change(function(e) {
      var checkbox;
      checkbox = $(e.currentTarget);
      if (checkbox.prop('checked')) {
        return checkbox.parents('.message').addClass('active');
      } else {
        return checkbox.parents('.message').removeClass('active');
      }
    });
  };

  init_search_box = function() {
    var search_box, search_input;
    search_box = $('.search-box');
    search_input = $('.search-box input[type="search"]');
    search_input.focus(function() {
      return search_box.addClass('focus');
    });
    return search_input.blur(function() {
      return search_box.removeClass('focus');
    });
  };

  init_sidebar = function() {
    return $('.sidebar-links li a').click(function(e) {
      var link;
      link = $(e.currentTarget);
      if (link.attr("data-target") === void 0) {
        $('.sidebar-links li').removeClass('active');
        return $(e.currentTarget.parentNode).addClass('active');
      }
    });
  };

  resize_main_pane = function() {
    return $('.main-pane').css('width', $(window).width() - $('.sidebar').outerWidth());
  };

  $(function() {
    init_dropdown();
    init_message_list();
    init_search_box();
    init_sidebar();
    resize_main_pane();
    return $(window).resize(resize_main_pane);
  });

}).call(this);
