# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7deec8955082dbca8c3d49d4409e9c209e465d70aed2fb1b5384e1c7f5d7068b44c9148d9a6ac6fcec788f6d923b23d39d7a9479ffecff4e73c59bf454853fd

test:
  secret_key_base: 4bb61c2c11f4654b6a727f8c48f762be1a9f5a2dc66f6e3d981d508562bd52bd49a4544ff5467323a91a9138df25ae85e7f663226bafe6fc48b91312d34c830c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
