#!/usr/bin/env bundle
# encoding: utf-8

ruby "2.1.2"

source "https://rubygems.org"

# TODO: ENABLE WHEN READY
# gemspec

group :development, :test do
  gem 'terminal-notifier-guard'
  gem "guard", "~> 2.6.1"
  gem "guard-rspec", "~> 4.3.1", require: false
  gem "rspec", "~> 3.0.0"
  gem 'coveralls', require: false
end

gem 'extlib'