# guard :shell, notification: true do
#   watch(%r{^lib/(.+)\.rb}) do |m|
#     n m[0], "Rubocop:"
#     `rake "rubocop[#{m[0]}]"`
#   end
# end

guard :rspec, cmd: 'bundle exec rspec --tty --color', notification: true, all_on_start: true do
  watch(%r{^(.+)\.rb})     { 'spec' }
  watch('spec/spec_helper.rb') { 'spec' }
  watch('spec/stubs_spec.rb')  { 'spec' }
end
