# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21dffbc00c78985c2582fece275a5dfe0fc3ced72b85a1cec85a0cf4c0eb405ebe3c3e77e917d0e4e630204233efa4a7a62d2aaace406a7c396d7af0c698ebec
  artsy_key: JvTPWe4WsQO-xqX6Bts49r-gJhV5iyvi8S2Ilpt8RxnMHJ5fG_aICfxlHmjeISgotisSOniXW0tdWJqOkPtJJcFJVvMnjjNJ1-AP-wTAf2cKVz8t5I1K7Uvrq8gV7FR_DSoAM2UeO78aWa2l0Be2qzNrkUEvQ8KZys9wEBiOwTeJj0hO8k6yOcRGgR4JFHciSZq-uBV5Ehq0qWC317c7U_GiJ2j3rSTBPKT0BgYJbnE=

test:
  secret_key_base: 2179d9bb3ad0bdd318761336ffdcbd5748688a60f259bf995186f8c0bd2b03cd38a6d08e094d4e4aa6f213e622df595ad739aaf71f0b575a9e1395c753de8073
  artsy_key: JvTPWe4WsQO-xqX6Bts49r-gJhV5iyvi8S2Ilpt8RxnMHJ5fG_aICfxlHmjeISgotisSOniXW0tdWJqOkPtJJcFJVvMnjjNJ1-AP-wTAf2cKVz8t5I1K7Uvrq8gV7FR_DSoAM2UeO78aWa2l0Be2qzNrkUEvQ8KZys9wEBiOwTeJj0hO8k6yOcRGgR4JFHciSZq-uBV5Ehq0qWC317c7U_GiJ2j3rSTBPKT0BgYJbnE=

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
