inherit_from:
  -  ../../.rubocop.yml
AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'lib/tasks/*'
    - 'script/**/*'
    - 'features/support/env.rb'
    - 'bin/spring'
    - !ruby/regexp /old_and_unused\.rb$/