source 'https://rubygems.org'
# ruby '1.9.3'

gem 'rails', '4.1.6'
gem 'pg'

# timezone sheeeyat for windows
gem 'tzinfo-data', platforms: [:mingw, :mswin]

gem 'jquery-rails'
gem 'turbolinks'
gem 'spring',        group: :development, platforms: [:ruby]
gem "rest-client"

group :test do
  # database_cleaner is not required, but highly recommended
  gem 'database_cleaner'

  gem 'cucumber', '~> 1.3', require: false
  gem 'cucumber-rails', require: false

  gem 'simplecov',        '~> 0.9', require: false
  gem 'simplecov-rcov',   '~> 0.2', require: false

  gem 'rubocop', github: 'bbatsov/rubocop'
  gem 'rubocop-rspec'

  gem 'webmock', '~> 1.18', require: false

  gem 'faker'
  gem 'capybara'
  gem 'guard-rspec'
  gem 'launchy'
end

group :development, :test do
  gem 'vcr'
  gem 'factory_girl_rails'
  gem 'rspec-rails', '~> 3.0.0'
end
