# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Artist.create([
  {
    first_name: 'Pablo',
    last_name: 'Picasso',
    biography: "Born in Málaga, Spain, in 1881, Pablo Picasso showed an early passion for drawing. His father, an art teacher, began giving him lessons in figure drawing and oil painting at the age of seven. Picasso enrolled in the School of Fine Arts in Barcelona and then at Madrid, but withdrew from formal training in 1899 to return to Barcelona, where he worked as a graphic artist. In 1900, Picasso made his first visit to Paris, and until 1904, he split his time between Paris and Barcelona.\n\nLate in 1901, Picasso began making paintings on themes of desolation and despair, depicting solitary and melancholy figures in paintings flooded with blue. In 1904, Picasso began his Rose Period, lightening his palette from the dark, moody blues of the previous years in favor of beige, red, and rose tones. Casting aside the melancholy subjects of the Blue Period, Picasso painted circus perform- ers, harlequins, and clowns.\n\nAfter meeting Georges Braque in 1907, Picasso and Braque worked closely together to develop Cubism. By 1910, they had developed a distinctive Cubist idiom, fracturing their subjects into small, faceted forms and working with a muted palette. Rejecting the traditional depiction of three-dimensional objects from one viewpoint, they instead represented the subject from a multitude of perspectives. In 1912, Picasso and Braque began experimenting with collage and papier collé, introducing real elements, such as newsprint, artificial wood, and wallpaper, into their paintings to achieve trompe-l’oeil effects. By 1911–12, Cub- ism had become popular as the latest avant-garde movement and progressive painters across Europe began painting in Cubist styles.\n\nAfter the upheaval of World War One, Picasso - together with other European artists including André Derain, Giorgio de Chirico, and Fernand Léger - returned to a more traditional artistichis exploration of Cubism, often painting works in remarkably different styles in a period of only a few hours.\nBy 1927, Picasso began experimenting with Surrealist imagery, incorporating morphed and distorted figures in his paintings. When the Spanish Civil War broke out in 1936, Picasso reacted with explicit, emotional works, painting the masterpiece Guernica in response to the bombing of the town by the fascist Generalissimo Francisco Franco in 1937.\n\nFrom the late 1940s through the 1960s, Picasso worked primarily in the south of France, where he painted, made ceramics, and experimented with printmaking. In the 1950s, Picasso began reinterpreting the work of the great masters, making paintings based on Velázquez, Goya, Manet, Courbet, and Delacroix. During the 1950s, Picasso’s international fame increased greatly with large exhibitions and retrospectives across the world. He continued to work prolifically through his eighties and nineties. He died in 1973, leaving behind an unparalleled legacy that has shaped the development of modern and contemporary art.",
    nationality: 'Spanish',
    analysis: "A prolific and tireless innovator of art forms, Pablo Picasso impacted the course of 20th-century art with unparalleled magnitude. Inspired by Primitivism and developments in the world around him, Picasso contributed significantly to a number of artistic movements, notably [Cubism](/gene/cubism), [Surrealism](/gene/surrealism), [Neoclassicism](/gene/neoclassicism), and [Expressionism](/gene/austrian-and-german-expressionism). Along with [Georges Braque](/artist/georges-braque), Picasso is best known for pioneering [Cubism](/gene/cubism) in an attempt to reconcile three-dimensional space with the two-dimensional picture plane, once asking, “Are we to paint what’s on the face, what’s inside the face, or what’s behind it?” Responding to the Spanish Civil War, he painted his most famous work, _Guernica_ (1937), whose violent images of anguished figures rendered in grisaille made it a definitive work of anti-war art. “Painting is not made to decorate apartments,” he said. “It’s an offensive and defensive weapon against the enemy.” Picasso’s sizable oeuvre includes over 20,000 paintings, prints, drawings, sculptures, ceramics, theater sets, and costume designs.",
    thumbnail: 'http://static0.artsy.net/artist_images/52f6bddd4a04f5d504f69c29/four_thirds.jpg',
    api_id: '4d8b928b4eb68a1b2c0001f2',
    birthyear: '1881'
  },
  {
    first_name: 'Claude',
    last_name: 'Monet',
    biography: "Claude Monet, born Oscar Claude Monet (14 November 1840 \u0096 5 December 1926) was a founder of French impressionist painting, and the most consistent and prolific practitioner of the movement's philosophy of expressing one's perceptions before nature, especially as applied to plein-airlandscape painting. The term Impressionism is derived from the title of his painting Impression, Sunrise (Impression, soleil levant).",
    nationality: 'French',
    analysis: "A founding member of the [Impressionist](/gene/impressionism) movement in the late 1800s, Claude Monet was interested in direct observation and perceptual study, particularly depicting the effects of light and shadow on color. A proponent of en plein air painting, Monet is most famous for his series depicting haystacks (1891), poplars (1892), the Rouen Cathedral (1894), and water lilies (1910-20). In each series, Monet painted the same site repeatedly, recording how the appearance changed as the light shifted. His final mural-sized paintings depicting the pond on his Giverny estate feature water lilies and water emerging from almost-abstract compositions of broad strokes of bright color and intricately built-up textures. Shortly after Monet died at age 86, the French government installed his last water-lilies series in specially constructed galleries at the Orangerie in Paris, where they remain today.",
    thumbnail: 'http://static2.artsy.net/artist_images/52f6bde44a04f5d504f6a44e/1/four_thirds.jpg',
    api_id: '4d8b92774eb68a1b2c000134',
    birthyear: '1840'
  },
  {
    first_name: 'Edward',
    last_name: 'Hopper',
    biography: "Perhaps the preeminent realist painter of the 20th century, Hopper is known for austere scenes that convey a sense of isolation. He ignored emerging developments in modern painting, instead choosing to focus on a pared-down representational style remarkable for its purity of form. Featuring subject matter that includes late nineteenth-century architecture, coastal views, and scenes and motifs of the modern city, Hopper's works possess a strangely empty character. Even when he depicts groups of individuals, they seem disconnected, lost in their own thoughts. Likewise, his scenes of solitary buildings, presented out of their full contexts and depicted from unconventional viewpoints, convey a sense of rootlessness. \n\nHopper, who was born in Nyack, New York, was not prolific, and produced only a few finished paintings each year. He relied heavily upon drawings to bring ideas to satisfactory completion in his finished oils. Although rarely exhibited during his lifetime, these drawings represent a crucial step in his creative process, and earned him admiration among fellow artists, who marveled at his ability to produce brilliant sketches upon demand. Hopper was also a highly accomplished illustrator (which is how he earned his living before finding success as an artist), etcher, and watercolorist.",
    nationality: 'American',
    analysis: "Edward Hopper defined 20th-century realism with his austere, eerie scenes that conveyed the alienation and isolation of modern life. _Nighthawks_ (1942), a painting of three customers sitting at the counter of a diner late at night, is among his most famous works. The illusion of light pervades his paintings, which depict late 19th-century architecture, coastal views, and scenes of the city. Hopper’s characters, even when painted in groups, seem disconnected and lost in thought. \"Great art is the outward expression of an inner life in the artist, and this inner life will result in his personal vision of the world,\" he said.",
    thumbnail: 'http://static1.artsy.net/artist_images/52f6bde14a04f5d504f6a2e3/1/four_thirds.jpg'
    api_id: '4d8b92a34eb68a1b2c000322',
    birthyear: '1882'
  },
  {
    first_name: 'Paul',
    last_name: 'Cézanne',
    biography: "Paul Cézanne (19 January 1839 \u0096 22 October 1906) was a French artist and Post-Impressionist painter whose work laid the foundations of the transition from the 19th century conception of artistic endeavor to a new and radically different world of art in the 20th century. Cézanne can be said to form the bridge between late 19th century Impressionism and the early 20th century's new line of artistic enquiry, Cubism. The line attributed to both Matisse and Picasso that Cézanne \"is the father of us all\" cannot be easily dismissed. Cézanne's work demonstrates a mastery of design, colour, composition and draftsmanship. His often repetitive, sensitive and exploratory brushstrokes are highly characteristic and clearly recognizable. He used planes of colour and small brushstrokes that build up to form complex fields, at once both a direct expression of the sensations of the observing eye and an abstraction from observed nature. The paintings convey Cézanne's intense study of his subjects, a searching gaze and a dogged struggle to deal with the complexity of human visual perception.",
    nationality: 'French',
    analysis: "Paul Cézanne is one of the great [Post-Impressionist](/gene/post-impressionism) painters of the 19th century, renowned for his radiant landscapes, intense portraits, and complex still lifes. His influence extends to every aspect of Post-Impressionist inquiry, from the search for empirical truth in painting, which he saw as including imbalance and lacunae, to the capturing of the instantaneity of vision, and the calling of attention to the dimensionality of the canvas space. His paintings of apples, card players, and the landscape of Mount Sainte Victoire, which he saw from his window in Provence, France, are some of the best-known images in Western art. His mature works are striking for their vivid palette, sensitive brushstrokes, and swirling, unstable compositions full of impetuosity and vigor that paved the way for the advent of [Cubism](/gene/cubism) and abstract painting.",
    thumbnail: 'http://static3.artsy.net/artist_images/52f6bddd4a04f5d504f69bd8/four_thirds.jpg'
    api_id: '4d8b92624eb68a1b2c00006c',
    birthyear: '1839'
  }
])
