#!/usr/bin/env bundle
# encoding: utf-8

ruby '2.1.2'

source 'https://rubygems.org'

gem 'abanalyzer'

group :development, :test do
  gem 'coveralls', require: false
  gem 'guard', require: false
  gem 'guard-rspec', require: false
  gem 'guard-rubocop', require: false
  gem 'guard-shell', require: false
  gem 'rspec', require: false
  gem 'rubocop', require: false
  gem 'terminal-notifier-guard', require: false
end
