source 'https://rubygems.org'

gem 'rails', '4.1.8'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'congress'
gem 'kaminari'
gem 'foundation-rails', '5.4.0'
gem 'devise'
gem 'simple_form'

group :doc do
  gem 'sdoc', '~> 0.4.0'
end

group :development do
  gem 'spring'
  gem 'guard-rspec', require: false
  gem 'guard-livereload', require: false
  gem "rack-livereload"
  gem "guard-cucumber"
end

group :test do
  gem 'cucumber-rails', require: false
  gem 'capybara'
  gem 'database_cleaner'
  gem 'webmock'
  gem 'shoulda-matchers'
end

group :development, :test do
  gem 'rspec-rails', '~> 3.0'
  gem 'vcr'
  gem 'factory_girl_rails'
  gem 'dotenv-rails'
  gem 'faker'
end
