# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
  adapter: postgresql
  encoding: unicode
  database: cyoa_development
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: cyoa_test
  pool: 5
  timeout: 5000

