source 'https://rubygems.org'

gem 'rails', '4.2.3'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'

# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'haml'
gem 'haml-rails'
gem 'httparty'
gem 'devise'
gem 'redis'
gem 'redis-rails'
gem 'sidekiq'
gem 'activerecord-session_store'


group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'cucumber-rails', :require => false
  gem 'capybara', :require => false
end

