#!/usr/bin/env bundle
# encoding: utf-8

ruby '2.1.2'

source 'https://rubygems.org'

gem 'haml', require: false
gem 'sinatra', require: false
gem 'sinatra-contrib', require: false

group :development, :test do
  gem 'colorize', require: false
  gem 'coveralls', require: false
  gem 'cucumber', require: false
  gem 'guard', require: false
  gem 'guard-cucumber', require: false
  gem 'guard-rspec', require: false
  gem 'guard-rubocop', require: false
  gem 'guard-shell', require: false
  gem 'rspec', require: false
  gem 'rubocop', require: false
  gem 'terminal-notifier-guard', require: false
end
