# rubocop:disable all
require 'rubygems'

require 'rspec/core/rake_task'

require_relative 'test/support/system_helper.rb'

RSpec::Core::RakeTask.new(:spec)

task default: :guard

task :guard do
  run_command('bundle exec guard --no-interactions')
end

task :specs do
  Rake::Task[:rspec].invoke('spec')
end

task :rspec do |_, args|
  run_command("bundle exec rspec --tty --color #{args.join(' ')}")
end
# rubocop:enable all
