source "https://rubygems.org"

gem "rails", "4.1.6"
gem "pg"
gem "sass-rails", "~> 4.0.3"
gem "uglifier", ">= 1.3.0"
gem "coffee-rails", "~> 4.0.0"
gem "haml"

gem "jquery-rails"
gem "turbolinks"
gem "jbuilder", "~> 2.0"

gem "grooveshark"

group :development do
  gem "spring"
  gem "better_errors"
end

group :development, :test do
  gem "rspec-rails"
  gem "factory_girl_rails"
end

group :test do
  gem "selenium-webdriver", "2.35.1"
  gem "capybara"
end

group :doc do
  gem "sdoc", "~> 0.4.0"
end

group :production do
  gem "rails_12factor", "0.0.2"
end
